### ISSUE TITLE
Cross-Complie with Lazarus

### ISSUE THREAD

**Issue by saja456-saja456** [JPeterMugaas/TaurusTLS#79]
We have following Problem:
We installed the TarusTLS Package like explained in the readme on Lazraus 4.2. We can use it for the Version of Lazarus which it is installed e.g linux lazraus can complie linux project. Windows 64bit can compile Windows 64bit and the same for 32bit ond Windows. But the Problem start if we want  crosscompile. So like from linux to any Windows or from Windows 64bit to Windows 32bit. We get:"TaurusTLSHeaders_x509.pas(22,36) Error: Can't find unit TaurusTLSHeaders_x509 used by TaurusTLSHeaders_x509v3" The IDE goes in the File " TaurusTLSHeaders_x509" at line 22.

For Linux we used Debian 12 and 13 with Lazarus from the website. For Crosscompile we use the Articel from the Lazarus Wiki. For Windows we use Win11 and Lazraus from the website too.

I dont know we do something wrong or just overlook something or it just isn't possible to crosscompile with the Package.

Thank You for your Work.

**Comment by tregubovav-dev** [comment]
Do you use standard compiler included to the Lazarus installation (fpc-3.2.2) ?

**Comment by saja456-saja456** [comment]
Yes we use fpc 3.2.2 on Linux and Windows. I forgot to mention it.

**Comment by saja456-saja456** [comment]
I just installed a new Server
1. Installation Debian 12 on Proxmox with official Template
2. Updating and bring it up to date
3. Installing LXDE
4. Download Lazarus https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%204.2/
5. apt install ./fpc-laz_3.2.2-210709_amd64.deb
6. apt install ./fpc-src_3.2.2-210709_amd64.deb
7. apt install ./lazarus-project_4.2.0-0_amd64.deb
8. Cross Compile after https://wiki.freepascal.org/Cross_compiling_for_Windows_under_Linux
9. Indylaz from online Packagemanager
10. download and unzip https://github.com/JPeterMugaas/TaurusTLS/archive/refs/tags/1.0.0.31beta31.tar.gz
11. Open TaurusTLSLDsgn
12. Open TaurusTLSRT and compile
13. compile TaurusTLSLSDsgn
14. install TaurusTLSLSDsgn
15. compile the project
But now i can even compile linux aginst linux i get instaly the error: 
Nachrichten, Warnungen: 4
Warning: other unit files search path (aka unit path) of "TaurusTLSLDsgn 1.0.0.31" contains "/home/task/TaurusTLS-1.0.0.31beta31/Source", which belongs to package "TaurusTLSRT"
Warning: other unit files search path (aka unit path) of "wst_indy 0.8" contains "/home/task/.lazarus/onlinepackagemanager/packages/wst", which belongs to package "wst_core"
Warning: other unit files search path (aka unit path) of "TaurusTLSRT 1.0.0.31" contains "/home/task/TaurusTLS-1.0.0.31beta31/Source", which belongs to package "TaurusTLSLDsgn"
Warning: other unit files search path (aka unit path) of "wst_core 0.8" contains "/home/task/.lazarus/onlinepackagemanager/packages/wst", which belongs to package "wst_indy"
Projekt kompilieren, Modus: Release, Ziel: /home/task/pascha/trunk/bin/x86_64-linux/Release/DB2DBc: Exit code 1, Fehler: 1, Warnungen: 1
Warning: Recompiling TaurusTLSHeaders_x509, checksum changed for /home/task/TaurusTLS-1.0.0.31beta31/Packages/lazarus/lib/x86_64-linux/TaurusTLSHeaders_crypto.ppu
TaurusTLSHeaders_x509.pas(9,67) Error: Can't find unit TaurusTLSHeaders_x509 used by TaurusTLSHeaders_x509v3
"

I dont know which Information you need to reproduce the Problem.

**Comment by JPeterMugaas** [comment]
I'm not sure what information I need because I doing something similar under Ubuntu and using development code.  I did notice that Lazarus was rebuilding Indy once and I fixed the path references in a project.  The project worked after fixing the paths.

I can see where Lazarus may have issues with file name case but I'm not sure if I am seeing that with your report.  It just sounds strange.

**Comment by saja456-saja456** [comment]
I was now able to compile TaurusFTPConsole from a Linux installation to win64. I needed to add under uses "interfaces". I will look tomorrow again in the code of the project, which doesnt crosscompile and will compare it with TaurusFTPConsole.

**Comment by saja456-saja456** [comment]
Sry i cant confirm this. I still have the same issue. I dont know, why but for some reason, it doesnt find it. If i include the "TaurusTLS/Source" as inculde unit in the projectoptions it works, but normally it should take this out of the package. I made today a new installtion of of a build server.

Here is a test project we have, which only contains the package. It still fails if i compile it for 32 bit on 64bit installtion with:
"
Nachrichten, Warnungen: 1
Warning: other unit files search path (aka unit path) of "TaurusTLSRT 1.0.0.31" contains "D:\git\TaurusTLS\Source", which belongs to package "TaurusTLSLDsgn"
Kompiliere Package FCL 1.0.1: Erfolg
Kompiliere Package LazUtils 1.0: Erfolg
Kompiliere Package LazDebuggerIntf 0.0.1: Erfolg
Kompiliere Package FreeTypeLaz 1.0: Erfolg
Kompiliere Package BuildIntf 1.0: Erfolg
Kompiliere Package DebuggerIntf 0.1: Erfolg
Kompiliere Package LCLBase 4.2: Erfolg
Kompiliere Package LCL 4.2: Erfolg
Kompiliere Package LazControls 1.0.1: Erfolg
Kompiliere Package IDEIntf 1.0: Erfolg
Kompiliere Package indylaz 10.6.2.4089: Erfolg
Kompiliere Package TaurusTLSRT 1.0.0.31: Erfolg
Projekt kompilieren, OS: win32, CPU: i386, Ziel: C:\Users\sascha\Downloads\TaurusTest\TaurusTest.exe: Exit code 1, Fehler: 1
TaurusTLSHeaders_x509.pas(9,9) Error: Can't find unit TaurusTLSHeaders_x509 used by TaurusTLSHeaders_x509v3
"
Maybe i make a fundamental error, which i dont see.
[TaurusTest.zip](https://github.com/user-attachments/files/21958700/TaurusTest.zip)

**Comment by JPeterMugaas** [comment]
I got the following error:
Warning: Recompiling TaurusTLSHeaders_x509v3, checksum changed for C:\msys64\home\jpmugaas\TaurusTLS\Packages\lazarus\lib\i386-win32\TaurusTLSHeaders_x509.ppu

**Comment by saja456-saja456** [comment]
I have still the Problem. Sometime i get it randomly to crosscompile, but after i hit clean and compile it doesent work agian. Everytime i try to reproduce the worked crosscompile it doesnt work again.
Sometime it work on a clean lazarus installation to double compile the TaurusTLS and double compile TaurusDsgn, but both are not reliable ways to get it work.

**Comment by Arael1895** [comment]
I got the same problem. I see many hints and warnings in Lazarus while compiling the RT package. 
I'll look into resolving them. Maybe that coukd resolve the problem.

**Comment by JPeterMugaas** [comment]
There's a discussion about this issue at:
https://forum.lazarus.freepascal.org/index.php/topic,71957.0.html

**Comment by DirkJ67** [comment]
No. The master branch does not compile in Lazarus 4.2 (Linux). The version in the OPM (2025-08-29T03:19T+02:00) seems to work.

In the TaurusTLSCompilerDefines.inc file, line 1097 in the master branch says `{$DEFINE USE_INLINE}`. In the OPM, it says `{$UNDEF USE_INLINE}`.

I believe the line in the OPM is correct.

**Comment by JPeterMugaas** [comment]
Thanks.  I don't know how I missed it but I checked in the fix.

**Comment by DirkJ67** [comment]
I tested the master branch on Windows and it compiles correctly. A cross-compile from Windows x64 to Windows i386 also worked as expected.

Many thanks to everyone involved for their work.
